FROM node:16.3.0-alpine
WORKDIR /usr/src/app
COPY package.json package-lock.json ./
RUN npm install
RUN npm install -g @angular/cli@7.3.9

# add app
COPY . /usr/src/app
EXPOSE 4200
# start app
CMD ng serve --host 0.0.0.0